services:
    redis:
        image: redis:7-alpine
        container_name: spc-redis
        command:
            [
                'redis-server',
                '--appendonly',
                'yes',
                '--requirepass',
                '${REDIS_PASSWORD}',
                '--rename-command',
                'CONFIG',
                '',
            ]
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        restart: unless-stopped
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
    redis-data:
