export const INITIAL_MSG = 'init'
export const INCOMING = 'incom'
export const DELETE = 'delcom'
export const CHECK_MISSING = 'check'
export const PUSH_MSG = 'push'
export const DELETE_MSG = 'del'
export const USER_ONLINE = 'uOn'
export const USERS_ONLINE = 'usOn'
